exception: rename MetaDataKeyNotFoundError to InvalidMetadata
MetaDataKeyNotFoundError is no longer needed as we want to allow
dumping storage domain metadata even if some keys are missing.

Renaming to InvalidMetadata will allow using this exception in a more
generic way without having to add a new exception specifically for
cases where some keys are missing.

Signed-off-by: Roman Bednar <rbednar@redhat.com>
Bug-Url: https://bugzilla.redhat.com/187088
Change-Id: I462c9ea37c541f4d9e0b3e2ef8b20da950085c95